version: "3.8"

services:
    postgres:
        image: postgres:14-alpine
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=koteseni
            - POSTGRES_PASSWORD=koteseni
            - POSTGRES_DB=fitstagram
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
volumes:
    postgres_data:
