version: "3.8"

services:
    postgres:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fitstagram
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    backend:
        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - "8000:8000"

volumes:
    postgres_data:
