//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::group::Entity as Group;
pub use super::group_join_request::Entity as GroupJoinRequest;
pub use super::group_member::Entity as GroupMember;
pub use super::location::Entity as Location;
pub use super::post::Entity as Post;
pub use super::post_comment::Entity as PostComment;
pub use super::post_group_visibility::Entity as PostGroupVisibility;
pub use super::post_like::Entity as PostLike;
pub use super::post_tag::Entity as PostTag;
pub use super::post_user_visibility::Entity as PostUserVisibility;
pub use super::user::Entity as User;
pub use super::wall::Entity as Wall;
pub use super::wall_post::Entity as WallPost;
